export const SUPABASE_URL = 'https://bipaeijxntmtlvzdbrzm.supabase.co';
export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcGFlaWp4bnRtdGx2emRicnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg1NTIwMjYsImV4cCI6MjA0NDEyODAyNn0.ezhAVaRahnrTeckcL14NyKjnpm5Fxw2G0TubnkYkEnM';
